services:
  - type: web
    name: welcome-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROUP_INVITE_LINK
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: GROUP_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
